### ISSUE TITLE
Incompatible with Firefox's "Dark Appearance".

### ISSUE THREAD

**Issue by StavrosTsik** [charwick/ff-realtabs#1]
Hello there. You have made a beautiful theme. It reminds me of Firefox from the good old days. I want to use it but I found some issues (bugs ?) with Firefox's "Dark Appearance".

First of all, I found out that this theme is only **(?)** compatible **(?)** with **`"Automatic/Light"`** in **"General -> Language an Appearance -> Website appearance"** and with **`"System theme -> auto"`** and **`"Light"`** in **"Themes"** page.

![FF_Automatic](https://github.com/charwick/ff-realtabs/assets/96174036/ed200e4e-65d9-4912-a011-8372ff435d4c)
![FF_Light](https://github.com/charwick/ff-realtabs/assets/96174036/40641c5c-5a75-44a3-bbf7-83d366334aea)
![FF_Theme](https://github.com/charwick/ff-realtabs/assets/96174036/6bd98ffb-cda1-48ec-8288-e3ac85ad3790)

I like the area bellow "Bookmarks" toolbar to be dark, so, when I choose **`"Dark"`** in **"General -> Language an Appearance -> Website appearance"** and leave the **"Themes"** to **`"System theme -> auto"`** **OR** **`"Light"`**, then the area bellow "Bookmarks" toolbar becoming dark **EXCEPT** Firefox's  **`"(All) Settings"`** pages:

![FF_Dark_1](https://github.com/charwick/ff-realtabs/assets/96174036/7984e5d5-f102-484b-a780-bb617f60762b)
![FF_Dark_2](https://github.com/charwick/ff-realtabs/assets/96174036/792a3412-81ee-4315-8554-84801e1b53ae)
![FF_Dark](https://github.com/charwick/ff-realtabs/assets/96174036/8ca012f0-833f-4ed7-8800-5e21effb3e27)
![FF_Dark_3](https://github.com/charwick/ff-realtabs/assets/96174036/dfe3663e-7777-4a24-a922-ae471fb18524)
![FF_Dark_4](https://github.com/charwick/ff-realtabs/assets/96174036/6513f333-c694-4a21-a3b4-b4a3f77d7b29)
![FF_Dark_5](https://github.com/charwick/ff-realtabs/assets/96174036/192611b6-919c-4922-8f11-0cc1a04587a4)
![FF_Dark_6](https://github.com/charwick/ff-realtabs/assets/96174036/1ea11973-7a4a-4d3f-ae95-681db5126550)
![FF_Dark_7](https://github.com/charwick/ff-realtabs/assets/96174036/4cbc166c-6fb5-4c14-9c8a-aa4bf8b6e741)

Second, when I try a different theme in **Themes** page and then I switch back to **`"System theme -> auto"`** **OR** **`"Light"`**, the theme doesn't revert automatically to its previous state and the tabs look like they are fading. The only solution to this, is to restart Firefox:

![FF_No Theme](https://github.com/charwick/ff-realtabs/assets/96174036/bd4b9922-118e-44df-8785-5d7fa4650119)

Tested on Firefox 121, 122 and 123.0.1.

**Comment by charwick** [comment]
Thanks for the detailed documentation. I'll fiddle around with it and see if I can get the preferences page to work in both modes.

On the last problem, it looks like the issue is that changing the theme overrides the Firefox Colors plugin until the next restart. I've opened an issue with them: https://github.com/mozilla/FirefoxColor/issues/1061

**Comment by charwick** [comment]
Just pushed an update https://github.com/charwick/ff-realtabs/commit/ccacdc431391bc0cf6a91a290289d04bc26f9ec4 with a fix. Replace userContent.css with the [new version](https://github.com/charwick/ff-realtabs/blob/main/userContent.css) and see if that works.

**Comment by StavrosTsik** [comment]
Ok. I’ll check and post back. One question though. I also saw an update to the **`userChrome.css`** file. Should I update both or there is no need ? 😕

**Comment by charwick** [comment]
That update rounds the edges of the base of the tabs, so feel free to update that one too.

**Comment by StavrosTsik** [comment]
> Just pushed an update [ccacdc4](https://github.com/charwick/ff-realtabs/commit/ccacdc431391bc0cf6a91a290289d04bc26f9ec4) with a fix. Replace userContent.css with the [new version](https://github.com/charwick/ff-realtabs/blob/main/userContent.css) and see if that works.

@charwick 
Works like a charm on all pages..!!! Thanks for the fix... :blush::satisfied::smiley:

![Screenshot 2024-03-22 220251](https://github.com/charwick/ff-realtabs/assets/96174036/698ed872-57b7-45cd-b78f-0ecc019abb0c)
![Screenshot 2024-03-22 220333](https://github.com/charwick/ff-realtabs/assets/96174036/c225ca5e-bca0-4c9e-88a8-e8c31ecc9078)
![Screenshot 2024-03-22 220404](https://github.com/charwick/ff-realtabs/assets/96174036/c89df95c-c31c-46f1-ab7a-5105532de379)
![Screenshot 2024-03-22 220436](https://github.com/charwick/ff-realtabs/assets/96174036/22f2a4a3-94fb-4117-9fd4-bec34cdeb6fd)
![Screenshot 2024-03-22 220524](https://github.com/charwick/ff-realtabs/assets/96174036/de5ce104-d36b-4f59-8ace-fe4406fd1a8a)
![Screenshot 2024-03-22 220559](https://github.com/charwick/ff-realtabs/assets/96174036/cb27559f-2607-43cd-ac72-e5ea5a31ed87)
![Screenshot 2024-03-22 220651](https://github.com/charwick/ff-realtabs/assets/96174036/c1445544-d631-49bd-8587-7aee574740cf)
![Screenshot 2024-03-22 220725](https://github.com/charwick/ff-realtabs/assets/96174036/3189f012-859d-4c8e-8d10-60990e48ecad)




> That update rounds the edges of the base of the tabs, so feel free to update that one too.


I like it better this way.. :wink:

![Screenshot 2024-03-22 220803](https://github.com/charwick/ff-realtabs/assets/96174036/7b58fada-932a-48f5-9e4d-5a4f68138827)




> On the last problem, it looks like the issue is that changing the theme overrides the Firefox Colors plugin until the next restart. I've opened an issue with them: [mozilla/FirefoxColor#1061](https://github.com/mozilla/FirefoxColor/issues/1061)

I don't have high hopes for a fix any time soon. As I have seen, last interaction with a reported issue was on January 2023. A year ago. Since then 6 open issues haven't been answered. :disappointed::worried:

P.S1 I also like, how Firefox looks when using only the `css` files without the **"Firefox Color"** addon, with all **"Dark"** options. The shadows, the Bookmarks toolbar, e.t.c. :wink:

![Screenshot 2024-03-22 215242](https://github.com/charwick/ff-realtabs/assets/96174036/a5922c47-74d3-428c-83e0-e6e049794ee4)
![Screenshot 2024-03-22 215605](https://github.com/charwick/ff-realtabs/assets/96174036/b7153393-44f2-45ce-b428-2a0892bd8853)
![Screenshot 2024-03-22 215713](https://github.com/charwick/ff-realtabs/assets/96174036/e302f564-e0a0-4c4d-be97-63b1f3ba01f1)


P.S2 Also, something that caught my attention [here.](https://github.com/Aris-t2/CustomCSSforFx/discussions/606#discussioncomment-8871955) I don't know how that, will affect the future of this project. :confused::confused:
